CREATE SCHEMA IF NOT EXISTS taxi;
SET search_path TO taxi;

CREATE TABLE trip
(
    row_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VendorID SMALLINT,
    tpep_pickup_datetime TIMESTAMP NOT NULL,
    tpep_dropoff_datetime TIMESTAMP NOT NULL,
    passenger_count SMALLINT,
    trip_distance REAL,
    RatecodeID SMALLINT,
    store_and_fwd_flag VARCHAR(1),
    PULocationID SMALLINT,
    DOLocationID SMALLINT,
    payment_type SMALLINT,
    fare_amount MONEY,
    extra MONEY,
    mta_tax MONEY,
    tip_amount MONEY,
    tolls_amount MONEY,
    improvement_surcharge MONEY,
    total_amount MONEY,
    congestion_surcharge MONEY
);

COPY trip (
    VendorID,
    tpep_pickup_datetime,
    tpep_dropoff_datetime,
    passenger_count,
    trip_distance,
    RatecodeID,
    store_and_fwd_flag,
    PULocationID,
    DOLocationID,
    payment_type,
    fare_amount,
    extra,
    mta_tax,
    tip_amount,
    tolls_amount,
    improvement_surcharge,
    total_amount,
    congestion_surcharge
) FROM '/app/data/csv/yellow_tripdata_2021-01.csv'
DELIMITER ','
CSV HEADER;
