CREATE SCHEMA IF NOT EXISTS taxi;
SET search_path TO taxi;

CREATE TABLE zone
(
    row_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    LocationID SMALLINT,
    Borough VARCHAR,
    Zone VARCHAR,
    service_zone VARCHAR
);

COPY zone (
    LocationID,
    Borough,
    Zone,
    service_zone
) FROM '/app/data/csv/taxi+_zone_lookup.csv'
DELIMITER ','
CSV HEADER;
